### ISSUE TITLE
6126, syntax error, unexpected PARSEOP_NAME

### ISSUE THREAD

**Issue by Boubak729** [RehabMan/Laptop-DSDT-Patch#91]
Hi there, I have the some  issues with my DSDT. 
6126, syntax error, unexpected PARSEOP_NAME.
.........................................
    Name (SS1, 0x00)
    Name (SS2, 0x00)
    Name (SS3, One)
    One
    Name (SS4, One)
    One
    OperationRegion (GNVS, SystemMemory, 0x5FF57000, 0x072C)
    Field (GNVS, AnyAcc, Lock, Preserve)
..................................
I've deleted the "One" not working, and marqued the Ones as comment with "//" but it always return the error : 6126, syntax error, unexpected PARSEOP_NAME.
I use Catalina on a Thinkpad P51 i7 7700HQ, Quadro 1200, intelHD630 graphic, 24 Gig of RAM,.
Need some help.
Here my files

[DSDT.aml.zip](https://github.com/RehabMan/Laptop-DSDT-Patch/files/4257490/DSDT.aml.zip)
[DSDT.dsl.zip](https://github.com/RehabMan/Laptop-DSDT-Patch/files/4257489/DSDT.dsl.zip)
![Uploading Screen Shot 2020-02-26 at 3.36.00 PM.png…]()

**Comment by prud28** [comment]
26.02.2020, 21:22, "Boubak729" <notifications@github.com>:Hi there, I have the some issues with my DSDT.6126, syntax error, unexpected PARSEOP_NAME..........................................Name (SS1, 0x00)Name (SS2, 0x00)Name (SS3, One)OneName (SS4, One)OneOperationRegion (GNVS, SystemMemory, 0x5FF57000, 0x072C)Field (GNVS, AnyAcc, Lock, Preserve)..................................I've deleted the "One" not working, and marked the Ones as comment with "//" but it always return the error : 6126, syntax error, unexpected PARSEOP_NAME.I use Catalina on a Thinkpad P51 i7 7700HQ, Quadro 1200, intelHD630 graphic, 24 Gig of RAM,.Need some help.Here my filesDSDT.aml.zipDSDT.dsl.zip—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Boubak729** [comment]
Hi prud28, thanks for the correction. the dsl file working fine and I was able add for the screen brightness. But when try to a the battery patch I get 27 error and I stuck. 
Need some help to fix or there is another to do it I will give try. Thanks in advance.
My dsl file patched with battery  status file.txt

[DSDT.zip](https://github.com/RehabMan/Laptop-DSDT-Patch/files/4266577/DSDT.zip)
[DSDT_battery_status_patch.txt.zip](https://github.com/RehabMan/Laptop-DSDT-Patch/files/4266587/DSDT_battery_status_patch.txt.zip)
and the original dsl
[DSDT.zip](https://github.com/RehabMan/Laptop-DSDT-Patch/files/4266594/DSDT.zip)

**Comment by prud28** [comment]
laptop model?28.02.2020, 13:38, "Boubak729" <notifications@github.com>:Hi prud28, thanks for the correction. the dsl file working fine and I was able add for the screen brightness. But when try to a the battery patch I get 27 error and I stuck.
Need some help to fix or there is another to do it I will give try. Thanks in advance.
My dsl file patched with battery  status file.txt
DSDT.zip
DSDT_battery_status_patch.txt.zip
and the original dsl
DSDT.zip
